name: schedule
on: push
  #schedule:
    # This cron expression means "at every 5th minute"
    #- cron: '*/5 * * * *'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World! - MODIFIED TO PUSH"
